[package]
name = "lemmy_db_views_transaction"
publish = false
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "lemmy_db_views_transaction"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[features]
full = ["lemmy_db_schema/full"]

[dependencies]
lemmy_db_schema = { workspace = true, features = ["full"] }
lemmy_db_schema_file = { workspace = true }
lemmy_utils = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
ts-rs = { workspace = true, optional = true }
chrono = { workspace = true }
bigdecimal = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
lemmy_db_views_wallet = { workspace = true, features = ["full"] }
lemmy_db_views_local_user = { workspace = true, features = ["full"] }

[dev-dependencies]
tokio = { workspace = true }
serial_test = { workspace = true }