[package]
name = "lemmy_ws"
publish = false
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
lemmy_api_utils = { workspace = true }
lemmy_utils = { workspace = true, features = ["full"] }
actix-web = { workspace = true }
actix-ws = "0.3.0"
uuid = { workspace = true }
serde_json = { workspace = true }
log = "0.4.27"
tokio = { workspace = true }
serde = { workspace = true }
actix-rt = "2.10.0"
futures-util = "0.3.31"
actix = { workspace = true }
url = { workspace = true }
awc = "3.7.0"
rand = "0.9.1"
actix-broker = "0.4"
actix-web-actors = "4.1"
phoenix_channels_client = { workspace = true }
