[package]
name = "app_108jobs_db_views_site"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
full = [
    "app_108jobs_utils",
    "diesel",
    "diesel-async",
    "app_108jobs_db_schema/full",
    "app_108jobs_db_schema_file/full",
    "app_108jobs_db_views_person/full",
    "app_108jobs_db_views_post/full",
    "extism",
    "extism-convert",
    "anyhow",
]
ts-rs = [
    "dep:ts-rs",
    "app_108jobs_db_schema/ts-rs",
    "app_108jobs_db_schema_file/ts-rs",
    "app_108jobs_db_views_local_user/ts-rs",
    "app_108jobs_db_views_person/ts-rs",
    "app_108jobs_db_views_post/ts-rs",
]

[dependencies]
app_108jobs_db_schema = { workspace = true }
app_108jobs_utils = { workspace = true, optional = true }
app_108jobs_db_schema_file = { workspace = true }
app_108jobs_db_views_local_user = { workspace = true }
app_108jobs_db_views_person = { workspace = true }
app_108jobs_db_views_post = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true, optional = true }
diesel-async = { workspace = true, optional = true }
serde = { workspace = true }
serde_with = { workspace = true }
ts-rs = { workspace = true, optional = true }
url = { workspace = true }
extism = { workspace = true, optional = true }
extism-convert = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
validator = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
tokio = "1.45.1"
